In [1]:
from sklearn.neighbors import kneighbors_graph
import numpy as np 

In [21]:
def get_neighbor(idx,connectivity,points):
    neibor_idx=np.arange(len(points))[connectivity[idx]]
    return neibor_idx

In [27]:
X = [[0], [3], [1.5],[-0.5]]
X=np.array(X)
# X=np.random.random((200,60))

A = kneighbors_graph(X, 2, mode='connectivity', include_self=False).toarray().astype(bool)
get_neighbor(2,A,X)

array([0, 1])

In [2]:
x=np.array([[2,0,1],[3,1,1],[4,2,2],[5,3,2]],dtype="f8")
x=x-np.mean(x,axis=0)
print(x)

[[-1.5 -1.5 -0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5]
 [ 1.5  1.5  0.5]]


In [3]:
u,s,vt=np.linalg.svd(x)
# 因为s的最后一个特征值接近0，所以这里取两个特征值，
# 因此取vt的前两列，那么x被降维成：
x_=x@(vt[:2].T)
print(x_)

[[-2.17682365 -0.10695241]
 [-0.81790909  0.28464843]
 [ 0.81790909 -0.28464843]
 [ 2.17682365  0.10695241]]


In [5]:
print(vt.T)

[[ 6.79457280e-01  1.95800420e-01  7.07106781e-01]
 [ 6.79457280e-01  1.95800420e-01 -7.07106781e-01]
 [ 2.76903610e-01 -9.60897700e-01 -8.74247957e-19]]


In [4]:
# 重构 
x_@vt[:2]

array([[-1.5, -1.5, -0.5],
       [-0.5, -0.5, -0.5],
       [ 0.5,  0.5,  0.5],
       [ 1.5,  1.5,  0.5]])

In [10]:
x=np.array([[1.0,1.0,0.0],[1.0,0.9,0.0],[1.0,1.1,0.0]],dtype="f8")
X=x.T@x
eigvalues,eigvectors=np.linalg.eigh(X)
print(eigvalues)
print(eigvectors)

[0.         0.00998333 6.01001667]
[[ 0.         -0.70828431  0.70592729]
 [ 0.          0.70592729  0.70828431]
 [ 1.          0.          0.        ]]
