In [1]:
from sklearn.neighbors import kneighbors_graph
import numpy as np 

In [21]:
def get_neighbor(idx,connectivity,points):
    neibor_idx=np.arange(len(points))[connectivity[idx]]
    return neibor_idx

In [27]:
X = [[0], [3], [1.5],[-0.5]]
X=np.array(X)
# X=np.random.random((200,60))

A = kneighbors_graph(X, 2, mode='connectivity', include_self=False).toarray().astype(bool)
get_neighbor(2,A,X)

array([0, 1])

In [2]:
x=np.array([[2,0,1],[3,1,1],[4,2,2],[5,3,2]],dtype="f8")
x=x-np.mean(x,axis=0)
print(x)

[[-1.5 -1.5 -0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5]
 [ 1.5  1.5  0.5]]


In [3]:
u,s,vt=np.linalg.svd(x)
# 因为s的最后一个特征值接近0，所以这里取两个特征值，
# 因此取vt的前两列，那么x被降维成：
x_=x@(vt[:2].T)
print(x_)

[[-2.17682365 -0.10695241]
 [-0.81790909  0.28464843]
 [ 0.81790909 -0.28464843]
 [ 2.17682365  0.10695241]]


In [5]:
print(vt.T)

[[ 6.79457280e-01  1.95800420e-01  7.07106781e-01]
 [ 6.79457280e-01  1.95800420e-01 -7.07106781e-01]
 [ 2.76903610e-01 -9.60897700e-01 -8.74247957e-19]]


In [4]:
# 重构 
x_@vt[:2]

array([[-1.5, -1.5, -0.5],
       [-0.5, -0.5, -0.5],
       [ 0.5,  0.5,  0.5],
       [ 1.5,  1.5,  0.5]])

In [10]:
x=np.array([[1.0,1.0,0.0],[1.0,0.9,0.0],[1.0,1.1,0.0]],dtype="f8")
X=x.T@x
eigvalues,eigvectors=np.linalg.eigh(X)
print(eigvalues)
print(eigvectors)

[0.         0.00998333 6.01001667]
[[ 0.         -0.70828431  0.70592729]
 [ 0.          0.70592729  0.70828431]
 [ 1.          0.          0.        ]]


In [8]:
x=np.array([[1,2,3],[2,3,4]],dtype="f8")
norm_x=np.linalg.norm(x,axis=1,keepdims=True)
print(x/norm_x)
print(np.linalg.norm(x/norm_x,axis=1,keepdims=True))

[[0.26726124 0.53452248 0.80178373]
 [0.37139068 0.55708601 0.74278135]]
[[1.]
 [1.]]


In [ ]:
from sklearn.preprocessing import StandardScaler

In [8]:
def normalization(vec):
    std=np.linalg.norm(vec,axis=1,keepdims=True)
    vec=vec/std
    return vec
    

def get_domain_vector(vectors,include=0.9):
    vectors=normalization(vectors)
    U,S,VT=np.linalg.svd(vectors,full_matrices=False)
    energy=S**2
    total_energy=np.sum(energy)
    k=np.argmax(np.cumsum(energy)>include*total_energy)+1
    main_vec=VT[:k,:]

    mean_d=np.mean(vectors,axis=0)
    print(U)
    print(S)
    print(VT)

def get_main(vectors,include=0.9):
    vectors=normalization(vectors)
    cov=vectors.T@vectors
    eigenvalues, eigenvectors=np.linalg.eig(cov)
    sort_idx=np.argsort(eigenvalues)[::-1]
    sort_eigenvalues=eigenvalues[sort_idx]
    sort_eigenvectors=eigenvectors[:,sort_idx]

    total_energy=np.sum(sort_eigenvalues)
    k=np.argmax(np.cumsum(sort_eigenvalues)>include*total_energy)+1
    main_vec=sort_eigenvectors[:,:k]

    print(main_vec)
    print(sort_eigenvalues[:k])


x=np.array([
    [1,1],
    [3,0],
    [0,1],
    [2,2]
],dtype="f8")
# x=np.array([[2,0,0],[3,1,1],[4,2,2],[5,3,2]],dtype="f8")
get_main(x)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[3. 1.]


In [28]:
prob=np.array([0.1,0.2,0.5,0.2])
prob=prob/np.sum(prob)
cum_prob=np.cumsum(prob)
cum_prob=np.insert(cum_prob,0,0.0)
rand=0.9

print(cum_prob)
print(rand<cum_prob)
print(np.argmax(rand<cum_prob)-1)

[0.  0.1 0.3 0.8 1. ]
[False False False False  True]
3


In [3]:
x=np.array([1,2,3])
mask=2
x[~mask]

np.int64(1)